### ISSUE TITLE
When Goes back to Home page text lost space between words

### ISSUE THREAD

**Issue by ashehzadgec** [gmrchk/swup-gia-demo#6]
HI there

Finally built an awesome transition with but got a weird issue is that whenever I go back to index/ home page animation gets quite jumpy and text loses it space between words on this whole page. This does not happen on other pages.

I checked it on local and live server and results are same.

Attached for your reference.

I am using component approach as explained in the demo of this framework. I spent my whole day on this figuring out but could not do that.

Do you have any idea why is this happening and how this can be solved. I am stuck on this. 

![text space lost](https://user-images.githubusercontent.com/65112198/112768271-bd168180-9034-11eb-8b17-61a69e46851f.png)

![package json](https://user-images.githubusercontent.com/65112198/112768498-bccab600-9035-11eb-86c5-6f9140c0784a.png)

Regards,
Shehzad Asif

**Comment by daun** [comment]
Have you ever figured out the problem?

**Comment by ashehzadgec** [comment]
Yes. It was on my end.

**Comment by daun** [comment]
👍
